# Generated by Django 5.0.1 on 2024-02-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HARD", "Hard cover"), ("SOFT", "Soft cover")], max_length=4
            ),
        ),
    ]
