# Generated by Django 5.0.1 on 2024-02-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0002_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
